<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>annotations</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>UnityEngine</AssemblyName>
    <RootNamespace>UnityEngine</RootNamespace>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8625;CS8632;CS0067;CS0108;CS0114;CS0169;CS0414;CS0649;CS0660;CS0661;CS1998</NoWarn>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
